### ISSUE TITLE
Dependencies issue with torch 2.0.1

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/ARC-LoCoMoSeT#27]
See https://github.com/pytorch/pytorch/issues/100974

`torch` v2.0.1 causes GitHub actions to fail (but ok locally). Have changed torch and torchvision versions in `pyproject.toml` to this for now:

```toml
torch = "^2.0, !=2.0.1"
torchvision = "^0.15"
```
